// Code generated by protoc-gen-go. DO NOT EDIT.
// source: punchh/workflow/workflow.proto

package workflowpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Workflow is the base object of a workflow.
type Workflow struct {
	Root                 *Statement `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d8c7cf8ce9ac6, []int{0}
}

func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workflow.Unmarshal(m, b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return xxx_messageInfo_Workflow.Size(m)
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetRoot() *Statement {
	if m != nil {
		return m.Root
	}
	return nil
}

// Statement ...
type Statement struct {
	ActivityInvocation   *ActivityInvocation `protobuf:"bytes,1,opt,name=activity_invocation,json=activityInvocation,proto3" json:"activity_invocation,omitempty"`
	Sequence             *Sequence           `protobuf:"bytes,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Parallel             *Parallel           `protobuf:"bytes,3,opt,name=parallel,proto3" json:"parallel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d8c7cf8ce9ac6, []int{1}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetActivityInvocation() *ActivityInvocation {
	if m != nil {
		return m.ActivityInvocation
	}
	return nil
}

func (m *Statement) GetSequence() *Sequence {
	if m != nil {
		return m.Sequence
	}
	return nil
}

func (m *Statement) GetParallel() *Parallel {
	if m != nil {
		return m.Parallel
	}
	return nil
}

// Sequence ...
type Sequence struct {
	Statements           []*Statement `protobuf:"bytes,1,rep,name=statements,proto3" json:"statements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Sequence) Reset()         { *m = Sequence{} }
func (m *Sequence) String() string { return proto.CompactTextString(m) }
func (*Sequence) ProtoMessage()    {}
func (*Sequence) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d8c7cf8ce9ac6, []int{2}
}

func (m *Sequence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sequence.Unmarshal(m, b)
}
func (m *Sequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sequence.Marshal(b, m, deterministic)
}
func (m *Sequence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequence.Merge(m, src)
}
func (m *Sequence) XXX_Size() int {
	return xxx_messageInfo_Sequence.Size(m)
}
func (m *Sequence) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequence.DiscardUnknown(m)
}

var xxx_messageInfo_Sequence proto.InternalMessageInfo

func (m *Sequence) GetStatements() []*Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

// Parallel ...
type Parallel struct {
	Statements           []*Statement `protobuf:"bytes,1,rep,name=statements,proto3" json:"statements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Parallel) Reset()         { *m = Parallel{} }
func (m *Parallel) String() string { return proto.CompactTextString(m) }
func (*Parallel) ProtoMessage()    {}
func (*Parallel) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d8c7cf8ce9ac6, []int{3}
}

func (m *Parallel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parallel.Unmarshal(m, b)
}
func (m *Parallel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parallel.Marshal(b, m, deterministic)
}
func (m *Parallel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parallel.Merge(m, src)
}
func (m *Parallel) XXX_Size() int {
	return xxx_messageInfo_Parallel.Size(m)
}
func (m *Parallel) XXX_DiscardUnknown() {
	xxx_messageInfo_Parallel.DiscardUnknown(m)
}

var xxx_messageInfo_Parallel proto.InternalMessageInfo

func (m *Parallel) GetStatements() []*Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

// ActivityInvocation ...
type ActivityInvocation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            []string `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityInvocation) Reset()         { *m = ActivityInvocation{} }
func (m *ActivityInvocation) String() string { return proto.CompactTextString(m) }
func (*ActivityInvocation) ProtoMessage()    {}
func (*ActivityInvocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4d8c7cf8ce9ac6, []int{4}
}

func (m *ActivityInvocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityInvocation.Unmarshal(m, b)
}
func (m *ActivityInvocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityInvocation.Marshal(b, m, deterministic)
}
func (m *ActivityInvocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityInvocation.Merge(m, src)
}
func (m *ActivityInvocation) XXX_Size() int {
	return xxx_messageInfo_ActivityInvocation.Size(m)
}
func (m *ActivityInvocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityInvocation.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityInvocation proto.InternalMessageInfo

func (m *ActivityInvocation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ActivityInvocation) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *ActivityInvocation) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Workflow)(nil), "workflow.Workflow")
	proto.RegisterType((*Statement)(nil), "workflow.Statement")
	proto.RegisterType((*Sequence)(nil), "workflow.Sequence")
	proto.RegisterType((*Parallel)(nil), "workflow.Parallel")
	proto.RegisterType((*ActivityInvocation)(nil), "workflow.ActivityInvocation")
}

func init() { proto.RegisterFile("punchh/workflow/workflow.proto", fileDescriptor_0f4d8c7cf8ce9ac6) }

var fileDescriptor_0f4d8c7cf8ce9ac6 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0xe9, 0x3a, 0x46, 0xf3, 0xf4, 0xf4, 0x06, 0xd2, 0xc3, 0x90, 0xd2, 0x8b, 0x3b, 0x55,
	0xb0, 0x1f, 0x40, 0xf4, 0xe6, 0x41, 0x90, 0x78, 0x10, 0x3c, 0x28, 0x59, 0x89, 0xae, 0x98, 0x25,
	0x35, 0x7d, 0xdd, 0xf0, 0xab, 0xf9, 0xe9, 0x64, 0x31, 0xc9, 0x86, 0xc3, 0xcb, 0x6e, 0xef, 0xcf,
	0x2f, 0x3f, 0xde, 0x7b, 0x81, 0xf3, 0x6e, 0xd0, 0xcd, 0x72, 0x79, 0xb9, 0x31, 0xf6, 0xe3, 0x4d,
	0x99, 0x4d, 0x0c, 0xaa, 0xce, 0x1a, 0x32, 0x98, 0x85, 0xbc, 0xac, 0x21, 0x7b, 0xf2, 0x31, 0x5e,
	0xc0, 0xd8, 0x1a, 0x43, 0x79, 0x52, 0x24, 0xf3, 0x93, 0xab, 0x69, 0x15, 0x1f, 0x3d, 0x92, 0x20,
	0xb9, 0x92, 0x9a, 0xb8, 0x03, 0xca, 0xef, 0x04, 0x58, 0xac, 0xe1, 0x3d, 0x4c, 0x45, 0x43, 0xed,
	0xba, 0xa5, 0xaf, 0xd7, 0x56, 0xaf, 0x4d, 0x23, 0xa8, 0x35, 0xda, 0x5b, 0x66, 0x3b, 0xcb, 0x8d,
	0x87, 0xee, 0x22, 0xc3, 0x51, 0x1c, 0xd4, 0xb0, 0x82, 0xac, 0x97, 0x9f, 0x83, 0xd4, 0x8d, 0xcc,
	0x47, 0xce, 0x81, 0x7b, 0x93, 0xf8, 0x0e, 0x8f, 0xcc, 0x96, 0xef, 0x84, 0x15, 0x4a, 0x49, 0x95,
	0xa7, 0x7f, 0xf9, 0x07, 0xdf, 0xe1, 0x91, 0x29, 0xaf, 0x21, 0x0b, 0x16, 0xac, 0x01, 0xfa, 0xb0,
	0x47, 0x9f, 0x27, 0x45, 0xfa, 0xdf, 0xde, 0x7b, 0xd8, 0x56, 0x10, 0xb4, 0xc7, 0x09, 0x5e, 0x00,
	0x0f, 0x6f, 0x81, 0x08, 0x63, 0x2d, 0x56, 0xd2, 0xdd, 0x8d, 0x71, 0x17, 0xe3, 0x0c, 0x98, 0xb0,
	0xef, 0xc3, 0xaf, 0x7d, 0x54, 0xa4, 0x73, 0xc6, 0x77, 0x05, 0x3c, 0x83, 0x89, 0x95, 0xfd, 0xa0,
	0xc8, 0xed, 0xcd, 0xb8, 0xcf, 0x6e, 0x4f, 0x9f, 0x21, 0x4c, 0xd0, 0x2d, 0x16, 0x13, 0xf7, 0xe5,
	0xf5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x12, 0xf1, 0x97, 0x14, 0x02, 0x00, 0x00,
}
