# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: punchh/journeyapi/journey_api.proto

require 'google/protobuf'

require 'punchh/journey/journey_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("punchh/journeyapi/journey_api.proto", :syntax => :proto3) do
    add_message "journeyapi.CreateJourneyRequest" do
      optional :journey, :message, 1, "journey.Journey"
    end
    add_message "journeyapi.CreateJourneyResponse" do
      optional :id, :int64, 1
    end
    add_message "journeyapi.ReadJourneyRequest" do
      optional :id, :int64, 1
    end
    add_message "journeyapi.ReadJourneyResponse" do
      optional :journey, :message, 1, "journey.Journey"
    end
    add_message "journeyapi.DeleteJourneyRequest" do
      optional :id, :int64, 1
    end
    add_message "journeyapi.DeleteJourneyResponse" do
      optional :id, :int64, 1
    end
  end
end

module Journeyapi
  CreateJourneyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.CreateJourneyRequest").msgclass
  CreateJourneyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.CreateJourneyResponse").msgclass
  ReadJourneyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.ReadJourneyRequest").msgclass
  ReadJourneyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.ReadJourneyResponse").msgclass
  DeleteJourneyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.DeleteJourneyRequest").msgclass
  DeleteJourneyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("journeyapi.DeleteJourneyResponse").msgclass
end
