// Code generated by protoc-gen-go. DO NOT EDIT.
// source: punchh/journeyapi/journey_api.proto

package journeyapipb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	journey "github.com/nmartinpunchh/banshee/pb/punchh/journey"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateJourneyRequest represents a create workflow requests
type CreateJourneyRequest struct {
	Journey              *journey.Journey `protobuf:"bytes,1,opt,name=journey,proto3" json:"journey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateJourneyRequest) Reset()         { *m = CreateJourneyRequest{} }
func (m *CreateJourneyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJourneyRequest) ProtoMessage()    {}
func (*CreateJourneyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{0}
}

func (m *CreateJourneyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJourneyRequest.Unmarshal(m, b)
}
func (m *CreateJourneyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJourneyRequest.Marshal(b, m, deterministic)
}
func (m *CreateJourneyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJourneyRequest.Merge(m, src)
}
func (m *CreateJourneyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJourneyRequest.Size(m)
}
func (m *CreateJourneyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJourneyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJourneyRequest proto.InternalMessageInfo

func (m *CreateJourneyRequest) GetJourney() *journey.Journey {
	if m != nil {
		return m.Journey
	}
	return nil
}

// CreateJourneyResponse represents a response.
type CreateJourneyResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateJourneyResponse) Reset()         { *m = CreateJourneyResponse{} }
func (m *CreateJourneyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJourneyResponse) ProtoMessage()    {}
func (*CreateJourneyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{1}
}

func (m *CreateJourneyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJourneyResponse.Unmarshal(m, b)
}
func (m *CreateJourneyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJourneyResponse.Marshal(b, m, deterministic)
}
func (m *CreateJourneyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJourneyResponse.Merge(m, src)
}
func (m *CreateJourneyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJourneyResponse.Size(m)
}
func (m *CreateJourneyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJourneyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJourneyResponse proto.InternalMessageInfo

func (m *CreateJourneyResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// ReadJourneyRequest represents a read workflow requests
type ReadJourneyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadJourneyRequest) Reset()         { *m = ReadJourneyRequest{} }
func (m *ReadJourneyRequest) String() string { return proto.CompactTextString(m) }
func (*ReadJourneyRequest) ProtoMessage()    {}
func (*ReadJourneyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{2}
}

func (m *ReadJourneyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJourneyRequest.Unmarshal(m, b)
}
func (m *ReadJourneyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJourneyRequest.Marshal(b, m, deterministic)
}
func (m *ReadJourneyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJourneyRequest.Merge(m, src)
}
func (m *ReadJourneyRequest) XXX_Size() int {
	return xxx_messageInfo_ReadJourneyRequest.Size(m)
}
func (m *ReadJourneyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJourneyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJourneyRequest proto.InternalMessageInfo

func (m *ReadJourneyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// ReadJourneyResponse represents a response.
type ReadJourneyResponse struct {
	Journey              *journey.Journey `protobuf:"bytes,1,opt,name=journey,proto3" json:"journey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadJourneyResponse) Reset()         { *m = ReadJourneyResponse{} }
func (m *ReadJourneyResponse) String() string { return proto.CompactTextString(m) }
func (*ReadJourneyResponse) ProtoMessage()    {}
func (*ReadJourneyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{3}
}

func (m *ReadJourneyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJourneyResponse.Unmarshal(m, b)
}
func (m *ReadJourneyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJourneyResponse.Marshal(b, m, deterministic)
}
func (m *ReadJourneyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJourneyResponse.Merge(m, src)
}
func (m *ReadJourneyResponse) XXX_Size() int {
	return xxx_messageInfo_ReadJourneyResponse.Size(m)
}
func (m *ReadJourneyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJourneyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJourneyResponse proto.InternalMessageInfo

func (m *ReadJourneyResponse) GetJourney() *journey.Journey {
	if m != nil {
		return m.Journey
	}
	return nil
}

// DeleteJourneyRequest represents a read workflow requests
type DeleteJourneyRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJourneyRequest) Reset()         { *m = DeleteJourneyRequest{} }
func (m *DeleteJourneyRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJourneyRequest) ProtoMessage()    {}
func (*DeleteJourneyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{4}
}

func (m *DeleteJourneyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJourneyRequest.Unmarshal(m, b)
}
func (m *DeleteJourneyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJourneyRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJourneyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJourneyRequest.Merge(m, src)
}
func (m *DeleteJourneyRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJourneyRequest.Size(m)
}
func (m *DeleteJourneyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJourneyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJourneyRequest proto.InternalMessageInfo

func (m *DeleteJourneyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// DeleteJourneyResponse represents a response.
type DeleteJourneyResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJourneyResponse) Reset()         { *m = DeleteJourneyResponse{} }
func (m *DeleteJourneyResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJourneyResponse) ProtoMessage()    {}
func (*DeleteJourneyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da6ef01c2958796e, []int{5}
}

func (m *DeleteJourneyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJourneyResponse.Unmarshal(m, b)
}
func (m *DeleteJourneyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJourneyResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJourneyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJourneyResponse.Merge(m, src)
}
func (m *DeleteJourneyResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJourneyResponse.Size(m)
}
func (m *DeleteJourneyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJourneyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJourneyResponse proto.InternalMessageInfo

func (m *DeleteJourneyResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateJourneyRequest)(nil), "journeyapi.CreateJourneyRequest")
	proto.RegisterType((*CreateJourneyResponse)(nil), "journeyapi.CreateJourneyResponse")
	proto.RegisterType((*ReadJourneyRequest)(nil), "journeyapi.ReadJourneyRequest")
	proto.RegisterType((*ReadJourneyResponse)(nil), "journeyapi.ReadJourneyResponse")
	proto.RegisterType((*DeleteJourneyRequest)(nil), "journeyapi.DeleteJourneyRequest")
	proto.RegisterType((*DeleteJourneyResponse)(nil), "journeyapi.DeleteJourneyResponse")
}

func init() {
	proto.RegisterFile("punchh/journeyapi/journey_api.proto", fileDescriptor_da6ef01c2958796e)
}

var fileDescriptor_da6ef01c2958796e = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0xcd, 0x4b,
	0xce, 0xc8, 0xd0, 0xcf, 0xca, 0x2f, 0x2d, 0xca, 0x4b, 0xad, 0x4c, 0x2c, 0xc8, 0x84, 0x31, 0xe3,
	0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xb8, 0x10, 0xb2, 0x52, 0x32, 0xa8,
	0x1a, 0x60, 0x34, 0x44, 0xa5, 0x92, 0x13, 0x97, 0x88, 0x73, 0x51, 0x6a, 0x62, 0x49, 0xaa, 0x17,
	0x44, 0x38, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8b, 0x8b, 0x1d, 0xaa, 0x50, 0x82,
	0x51, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x40, 0x0f, 0xa6, 0x11, 0xa6, 0x12, 0xa6, 0x40, 0x49, 0x9d,
	0x4b, 0x14, 0xcd, 0x8c, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14,
	0xb0, 0x7e, 0xe6, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x15, 0x2e, 0xa1, 0xa0, 0xd4, 0xc4, 0x14, 0x34,
	0xab, 0xd0, 0x55, 0x39, 0x72, 0x09, 0xa3, 0xa8, 0x82, 0x1a, 0x46, 0x8a, 0x8b, 0xd4, 0xb8, 0x44,
	0x5c, 0x52, 0x73, 0x52, 0x31, 0x7c, 0x85, 0x6e, 0x95, 0x3a, 0x97, 0x28, 0x9a, 0x3a, 0xec, 0x2e,
	0x37, 0xea, 0x60, 0xe2, 0xe2, 0x82, 0xaa, 0x71, 0x0c, 0xf0, 0x14, 0x0a, 0xe1, 0xe2, 0x45, 0xf1,
	0xb1, 0x90, 0x82, 0x1e, 0x22, 0xc4, 0xf5, 0xb0, 0x05, 0xa8, 0x94, 0x22, 0x1e, 0x15, 0x50, 0x4b,
	0xfd, 0xb8, 0xb8, 0x91, 0x3c, 0x2e, 0x24, 0x87, 0xac, 0x03, 0x33, 0xdc, 0xa4, 0xe4, 0x71, 0xca,
	0x43, 0xcd, 0x0b, 0xe1, 0xe2, 0x45, 0xf1, 0x1d, 0xaa, 0x2b, 0xb1, 0x05, 0x10, 0xaa, 0x2b, 0xb1,
	0x06, 0x8d, 0x13, 0x5f, 0x14, 0x0f, 0x42, 0x4d, 0x41, 0x52, 0x12, 0x1b, 0x38, 0x21, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xae, 0xb5, 0xdf, 0x99, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JourneyAPIClient is the client API for JourneyAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JourneyAPIClient interface {
	// CreateJourney ...
	CreateJourney(ctx context.Context, in *CreateJourneyRequest, opts ...grpc.CallOption) (*CreateJourneyResponse, error)
	// ReadJourney ...
	ReadJourney(ctx context.Context, in *ReadJourneyRequest, opts ...grpc.CallOption) (*ReadJourneyResponse, error)
	// DeleteJourney ...
	DeleteJourney(ctx context.Context, in *DeleteJourneyRequest, opts ...grpc.CallOption) (*DeleteJourneyResponse, error)
}

type journeyAPIClient struct {
	cc *grpc.ClientConn
}

func NewJourneyAPIClient(cc *grpc.ClientConn) JourneyAPIClient {
	return &journeyAPIClient{cc}
}

func (c *journeyAPIClient) CreateJourney(ctx context.Context, in *CreateJourneyRequest, opts ...grpc.CallOption) (*CreateJourneyResponse, error) {
	out := new(CreateJourneyResponse)
	err := c.cc.Invoke(ctx, "/journeyapi.JourneyAPI/CreateJourney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journeyAPIClient) ReadJourney(ctx context.Context, in *ReadJourneyRequest, opts ...grpc.CallOption) (*ReadJourneyResponse, error) {
	out := new(ReadJourneyResponse)
	err := c.cc.Invoke(ctx, "/journeyapi.JourneyAPI/ReadJourney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journeyAPIClient) DeleteJourney(ctx context.Context, in *DeleteJourneyRequest, opts ...grpc.CallOption) (*DeleteJourneyResponse, error) {
	out := new(DeleteJourneyResponse)
	err := c.cc.Invoke(ctx, "/journeyapi.JourneyAPI/DeleteJourney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JourneyAPIServer is the server API for JourneyAPI service.
type JourneyAPIServer interface {
	// CreateJourney ...
	CreateJourney(context.Context, *CreateJourneyRequest) (*CreateJourneyResponse, error)
	// ReadJourney ...
	ReadJourney(context.Context, *ReadJourneyRequest) (*ReadJourneyResponse, error)
	// DeleteJourney ...
	DeleteJourney(context.Context, *DeleteJourneyRequest) (*DeleteJourneyResponse, error)
}

// UnimplementedJourneyAPIServer can be embedded to have forward compatible implementations.
type UnimplementedJourneyAPIServer struct {
}

func (*UnimplementedJourneyAPIServer) CreateJourney(ctx context.Context, req *CreateJourneyRequest) (*CreateJourneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJourney not implemented")
}
func (*UnimplementedJourneyAPIServer) ReadJourney(ctx context.Context, req *ReadJourneyRequest) (*ReadJourneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadJourney not implemented")
}
func (*UnimplementedJourneyAPIServer) DeleteJourney(ctx context.Context, req *DeleteJourneyRequest) (*DeleteJourneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJourney not implemented")
}

func RegisterJourneyAPIServer(s *grpc.Server, srv JourneyAPIServer) {
	s.RegisterService(&_JourneyAPI_serviceDesc, srv)
}

func _JourneyAPI_CreateJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JourneyAPIServer).CreateJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journeyapi.JourneyAPI/CreateJourney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JourneyAPIServer).CreateJourney(ctx, req.(*CreateJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JourneyAPI_ReadJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JourneyAPIServer).ReadJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journeyapi.JourneyAPI/ReadJourney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JourneyAPIServer).ReadJourney(ctx, req.(*ReadJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JourneyAPI_DeleteJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JourneyAPIServer).DeleteJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/journeyapi.JourneyAPI/DeleteJourney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JourneyAPIServer).DeleteJourney(ctx, req.(*DeleteJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JourneyAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "journeyapi.JourneyAPI",
	HandlerType: (*JourneyAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJourney",
			Handler:    _JourneyAPI_CreateJourney_Handler,
		},
		{
			MethodName: "ReadJourney",
			Handler:    _JourneyAPI_ReadJourney_Handler,
		},
		{
			MethodName: "DeleteJourney",
			Handler:    _JourneyAPI_DeleteJourney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "punchh/journeyapi/journey_api.proto",
}
