# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: punchh/journey/journey.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'punchh/workflow/workflow_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("punchh/journey/journey.proto", :syntax => :proto3) do
    add_message "journey.Journey" do
      optional :start_time, :message, 1, "google.protobuf.Timestamp"
      optional :end_time, :message, 2, "google.protobuf.Timestamp"
      optional :status, :enum, 3, "journey.Status"
      optional :segment_id, :string, 4
      optional :control_group_size, :int64, 5
      optional :guest_entry_limit, :int64, 6
      optional :workflow, :message, 7, "workflow.Workflow"
    end
    add_enum "journey.Status" do
      value :STATUS_INVALID, 0
      value :STATUS_DRAFT, 1
      value :STATUS_LIVE, 2
      value :STATUS_DISABLED, 3
    end
  end
end

module Journey
  Journey = Google::Protobuf::DescriptorPool.generated_pool.lookup("journey.Journey").msgclass
  Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("journey.Status").enummodule
end
